---
# ([string]) Paths to take for backup.
paths:
  - "/bin"
  - "/home/linux/Documents"
  - "/etc/hosts"
# (bool) Declare if wants to encrypt the folder with the backup.
encrypted: True
# (string) Password to encrypt the backup
encrypting_password: "test"
# (string) Declare if the backup will be stored locally or in a cloud environment.
source: "local"
# (string) Declare where the backup is stored.
destiny: "/media/linux/USB"
